exports.keys = {
    '* Private Price Guide': 'pricePrivate',
'* Trade In Price Guide': 'priceTrade',
'* Average Km': 'avgKm',
'* Price When New': 'priceNew',
'Price': 'priceNew',
'Drive': 'driveType',
'Badge': 'badge',
'Fuel Type': 'fuel',
'Series': 'series',
'Recommended RON Rating': 'recommendedFuel',
'Body': 'bodyType',
'Release Year': 'year',
'No. Doors': 'doors',
'VIN Number': 'vin',
'Seat Capacity': 'seats',
'Country of origin': 'countryOrigin',
'Transmission': 'transmission',
'Number of Gears': 'gears',
'Engine Location': 'engineLocation',
'Power': 'power',
'Configuration': 'engineConfiguration',
'Torque': 'torque',
'Engine Size (cc)': 'engineSize',
'Induction System': 'induction',
'Cam': 'cam',
'Engine Cycle': 'engineCycle',
'Fuel Tank Capacity (litres)': 'fuelCapacity',
'Engine Type': 'engineType',
'Fuel Delivery': 'fuelDelivery',
'Engine Number': 'engineNumber',
'Method of Delivery': 'deliverMethod',
'Engine Code': 'engineCode',
'Fuel Urban (l/100km)': 'fuelRatingUrban',
'Cylinders': 'cylinders',
'Carbon Dioxide (g/km)': 'carbonGramsPerKM',
'Valves per Cylinder': 'valvesPerCylinder',
'Fuel Extra Urban (l/100km)': 'fuelRatingExtraUrban',
'Compression Ratio': 'compression',
'Fuel Combined (l/100km)': 'fuelRatingCombined',
'Kerb Weight (kg)': 'weightKerb',
'Length (mm)': 'length',
'Tare Mass (kg)': 'weightTare',
'Width (mm)': 'width',
'Towing Braked (kg)': 'towingBrakedKg',
'Height (mm)': 'height',
'Towing Not Braked (kg)': 'towingKg',
'Track Front (mm)': 'trackFront',
'Wheel Base (mm)': 'wheelBase',
'Track Rear (mm)': 'trackRear',
'Warranty KM': 'warrantyKm',
'Warranty Years': 'warrantyYears',
'Steering Description': 'steering',
'Front - diameter( mm)': 'tyreFront',
'Front Rim Description': 'rimFront',
'Rim Material': 'rimMaterial',
'Gross Vehicle Mass (kg)': 'weightGross',
'Pay Load (kg)': 'payload',
'Gross Combination Mass (kg)': 'weightGrossCombined',
'Acceleration 0-100Km/h (secs)': 'accel'
};